In [ ]:
%matplotlib inline

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import copy

from scipy import stats

In [ ]:
import os
os.getcwd()

'/content'

In [ ]:
 # Outputs will be saved in your google drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# file input and output paths
input_path = '/content/drive/MyDrive/Colab Notebooks/Gradu/Data/Excel preprocessed/'
output_path = '/content/drive/MyDrive/Colab Notebooks/Gradu/Data/Python preprocessed/'

In [ ]:
financial_variables = ['oil', 'silver', 'eurusd', 'eurcfh', 'spx', 'omx']
macro_variables = ['inflation', 'unemployment', 'imports', 'exports', 'exchange', 'ppi', 'bci', 'cci', 'construction', 'manufacturing', 'world', 'share_prices']

In [ ]:
countries = ['Belgium', 'Denmark', 'Germany', 'Spain', 'France', 'Italy', 'Netherlands', 'Austria', 'Poland', 'Finland', 'Sweden', 'United States']

In [ ]:
for variable in financial_variables:
    input_file = input_path + variable + '.csv'
    output_file = output_path + variable + '.csv'

    data = pd.read_csv(input_file, header=0, index_col=0)
    data = data.astype(float) # set to float type
    data = data.drop(columns=['Open', 'High', 'Low', 'Vol.', 'Change ']) # drop columns
    data = data[::-1]
    data.index = pd.to_datetime(data.index, format = '%m/%d/%Y').strftime('%Y-%m')

    df_all = pd.DataFrame(index=data.index) # initialise with index in order to copy data over
    df_all = df_all.astype(float)
    for country in countries:
        df_all[country] = data["Price"]
    df_all.to_csv(output_file) # save to csv

    print(variable, df_all)

oil          Belgium  Denmark  Germany  Spain  France  Italy  Netherlands  \
Date
2000-01    25.97    25.97    25.97  25.97   25.97  25.97        25.97
2000-02    28.09    28.09    28.09  28.09   28.09  28.09        28.09
2000-03    24.77    24.77    24.77  24.77   24.77  24.77        24.77
2000-04    23.89    23.89    23.89  23.89   23.89  23.89        23.89
2000-05    28.31    28.31    28.31  28.31   28.31  28.31        28.31
...          ...      ...      ...    ...     ...    ...          ...
2022-08    95.64    95.64    95.64  95.64   95.64  95.64        95.64
2022-09    85.14    85.14    85.14  85.14   85.14  85.14        85.14
2022-10    94.83    94.83    94.83  94.83   94.83  94.83        94.83
2022-11    85.43    85.43    85.43  85.43   85.43  85.43        85.43
2022-12    85.91    85.91    85.91  85.91   85.91  85.91        85.91

         Austria  Poland  Finland  Sweden  United States
Date
2000-01    25.97   25.97    25.97   25.97          25.97
2000-02    28.09   28.09    28.09   28.09          28.09
2000-03    24.77   24.77    24.77   24.77          24.77
2000-04    23.89   23.89    23.89   23.89          23.89
2000-05    28.31   28.31    28.31   28.31          28.31
...          ...     ...      ...     ...            ...
2022-08    95.64   95.64    95.64   95.64          95.64
2022-09    85.14   85.14    85.14   85.14          85.14
2022-10    94.83   94.83    94.83   94.83          94.83
2022-11    85.43   85.43    85.43   85.43          85.43
2022-12    85.91   85.91    85.91   85.91          85.91

[276 rows x 12 columns]
silver          Belgium  Denmark  Germany   Spain  France   Italy  Netherlands  \
Date
2000-01    5.321    5.321    5.321   5.321   5.321   5.321        5.321
2000-02    5.108    5.108    5.108   5.108   5.108   5.108        5.108
2000-03    5.062    5.062    5.062   5.062   5.062   5.062        5.062
2000-04    5.015    5.015    5.015   5.015   5.015   5.015        5.015
2000-05    4.987    4.987    4.987   4.987   4.987   4.987        4.987
...          ...      ...      ...     ...     ...     ...          ...
2022-08   17.849   17.849   17.849  17.849  17.849  17.849       17.849
2022-09   19.039   19.039   19.039  19.039  19.039  19.039       19.039
2022-10   19.119   19.119   19.119  19.119  19.119  19.119       19.119
2022-11   21.781   21.781   21.781  21.781  21.781  21.781       21.781
2022-12   24.040   24.040   24.040  24.040  24.040  24.040       24.040

         Austria  Poland  Finland  Sweden  United States
Date
2000-01    5.321   5.321    5.321   5.321          5.321
2000-02    5.108   5.108    5.108   5.108          5.108
2000-03    5.062   5.062    5.062   5.062          5.062
2000-04    5.015   5.015    5.015   5.015          5.015
2000-05    4.987   4.987    4.987   4.987          4.987
...          ...     ...      ...     ...            ...
2022-08   17.849  17.849   17.849  17.849         17.849
2022-09   19.039  19.039   19.039  19.039         19.039
2022-10   19.119  19.119   19.119  19.119         19.119
2022-11   21.781  21.781   21.781  21.781         21.781
2022-12   24.040  24.040   24.040  24.040         24.040

[276 rows x 12 columns]
eurusd          Belgium  Denmark  Germany   Spain  France   Italy  Netherlands  \
Date
2000-01   0.9695   0.9695   0.9695  0.9695  0.9695  0.9695       0.9695
2000-02   0.9647   0.9647   0.9647  0.9647  0.9647  0.9647       0.9647
2000-03   0.9562   0.9562   0.9562  0.9562  0.9562  0.9562       0.9562
2000-04   0.9123   0.9123   0.9123  0.9123  0.9123  0.9123       0.9123
2000-05   0.9379   0.9379   0.9379  0.9379  0.9379  0.9379       0.9379
...          ...      ...      ...     ...     ...     ...          ...
2022-08   1.0057   1.0057   1.0057  1.0057  1.0057  1.0057       1.0057
2022-09   0.9799   0.9799   0.9799  0.9799  0.9799  0.9799       0.9799
2022-10   0.9883   0.9883   0.9883  0.9883  0.9883  0.9883       0.9883
2022-11   1.0405   1.0405   1.0405  1.0405  1.0405  1.0405       1.0405
2022-12   1.0702   1.0702   1.0702  1.0702  1.0702  1.0702       1.0702

         Austria  Poland  Finland  Sweden  United States
Date
2000-01   0.9695  0.9695   0.9695  0.9695         0.9695
2000-02   0.9647  0.9647   0.9647  0.9647         0.9647
2000-03   0.9562  0.9562   0.9562  0.9562         0.9562
2000-04   0.9123  0.9123   0.9123  0.9123         0.9123
2000-05   0.9379  0.9379   0.9379  0.9379         0.9379
...          ...     ...      ...     ...            ...
2022-08   1.0057  1.0057   1.0057  1.0057         1.0057
2022-09   0.9799  0.9799   0.9799  0.9799         0.9799
2022-10   0.9883  0.9883   0.9883  0.9883         0.9883
2022-11   1.0405  1.0405   1.0405  1.0405         1.0405
2022-12   1.0702  1.0702   1.0702  1.0702         1.0702

[276 rows x 12 columns]
eurcfh          Belgium  Denmark  Germany   Spain  France   Italy  Netherlands  \
Date
2000-01   1.6061   1.6061   1.6061  1.6061  1.6061  1.6061       1.6061
2000-02   1.6058   1.6058   1.6058  1.6058  1.6058  1.6058       1.6058
2000-03   1.5916   1.5916   1.5916  1.5916  1.5916  1.5916       1.5916
2000-04   1.5662   1.5662   1.5662  1.5662  1.5662  1.5662       1.5662
2000-05   1.5768   1.5768   1.5768  1.5768  1.5768  1.5768       1.5768
...          ...      ...      ...     ...     ...     ...          ...
2022-08   0.9830   0.9830   0.9830  0.9830  0.9830  0.9830       0.9830
2022-09   0.9670   0.9670   0.9670  0.9670  0.9670  0.9670       0.9670
2022-10   0.9894   0.9894   0.9894  0.9894  0.9894  0.9894       0.9894
2022-11   0.9840   0.9840   0.9840  0.9840  0.9840  0.9840       0.9840
2022-12   0.9893   0.9893   0.9893  0.9893  0.9893  0.9893       0.9893

         Austria  Poland  Finland  Sweden  United States
Date
2000-01   1.6061  1.6061   1.6061  1.6061         1.6061
2000-02   1.6058  1.6058   1.6058  1.6058         1.6058
2000-03   1.5916  1.5916   1.5916  1.5916         1.5916
2000-04   1.5662  1.5662   1.5662  1.5662         1.5662
2000-05   1.5768  1.5768   1.5768  1.5768         1.5768
...          ...     ...      ...     ...            ...
2022-08   0.9830  0.9830   0.9830  0.9830         0.9830
2022-09   0.9670  0.9670   0.9670  0.9670         0.9670
2022-10   0.9894  0.9894   0.9894  0.9894         0.9894
2022-11   0.9840  0.9840   0.9840  0.9840         0.9840
2022-12   0.9893  0.9893   0.9893  0.9893         0.9893

[276 rows x 12 columns]
spx          Belgium  Denmark  Germany    Spain   France    Italy  Netherlands  \
Date
2000-01  1394.46  1394.46  1394.46  1394.46  1394.46  1394.46      1394.46
2000-02  1366.42  1366.42  1366.42  1366.42  1366.42  1366.42      1366.42
2000-03  1498.58  1498.58  1498.58  1498.58  1498.58  1498.58      1498.58
2000-04  1452.43  1452.43  1452.43  1452.43  1452.43  1452.43      1452.43
2000-05  1420.60  1420.60  1420.60  1420.60  1420.60  1420.60      1420.60
...          ...      ...      ...      ...      ...      ...          ...
2022-08  3955.00  3955.00  3955.00  3955.00  3955.00  3955.00      3955.00
2022-09  3585.62  3585.62  3585.62  3585.62  3585.62  3585.62      3585.62
2022-10  3871.98  3871.98  3871.98  3871.98  3871.98  3871.98      3871.98
2022-11  4080.11  4080.11  4080.11  4080.11  4080.11  4080.11      4080.11
2022-12  3839.50  3839.50  3839.50  3839.50  3839.50  3839.50      3839.50

         Austria   Poland  Finland   Sweden  United States
Date
2000-01  1394.46  1394.46  1394.46  1394.46        1394.46
2000-02  1366.42  1366.42  1366.42  1366.42        1366.42
2000-03  1498.58  1498.58  1498.58  1498.58        1498.58
2000-04  1452.43  1452.43  1452.43  1452.43        1452.43
2000-05  1420.60  1420.60  1420.60  1420.60        1420.60
...          ...      ...      ...      ...            ...
2022-08  3955.00  3955.00  3955.00  3955.00        3955.00
2022-09  3585.62  3585.62  3585.62  3585.62        3585.62
2022-10  3871.98  3871.98  3871.98  3871.98        3871.98
2022-11  4080.11  4080.11  4080.11  4080.11        4080.11
2022-12  3839.50  3839.50  3839.50  3839.50        3839.50

[276 rows x 12 columns]
omx           Belgium   Denmark   Germany     Spain    France     Italy  \
Date
2000-01  14992.53  14992.53  14992.53  14992.53  14992.53  14992.53
2000-02  16302.55  16302.55  16302.55  16302.55  16302.55  16302.55
2000-03  16685.79  16685.79  16685.79  16685.79  16685.79  16685.79
2000-04  17734.50  17734.50  17734.50  17734.50  17734.50  17734.50
2000-05  15833.28  15833.28  15833.28  15833.28  15833.28  15833.28
...           ...       ...       ...       ...       ...       ...
2022-08  10678.87  10678.87  10678.87  10678.87  10678.87  10678.87
2022-09   9934.81   9934.81   9934.81   9934.81   9934.81   9934.81
2022-10  10396.02  10396.02  10396.02  10396.02  10396.02  10396.02
2022-11  11069.81  11069.81  11069.81  11069.81  11069.81  11069.81
2022-12  10807.78  10807.78  10807.78  10807.78  10807.78  10807.78

         Netherlands   Austria    Poland   Finland    Sweden  United States
Date
2000-01     14992.53  14992.53  14992.53  14992.53  14992.53       14992.53
2000-02     16302.55  16302.55  16302.55  16302.55  16302.55       16302.55
2000-03     16685.79  16685.79  16685.79  16685.79  16685.79       16685.79
2000-04     17734.50  17734.50  17734.50  17734.50  17734.50       17734.50
2000-05     15833.28  15833.28  15833.28  15833.28  15833.28       15833.28
...              ...       ...       ...       ...       ...            ...
2022-08     10678.87  10678.87  10678.87  10678.87  10678.87       10678.87
2022-09      9934.81   9934.81   9934.81   9934.81   9934.81        9934.81
2022-10     10396.02  10396.02  10396.02  10396.02  10396.02       10396.02
2022-11     11069.81  11069.81  11069.81  11069.81  11069.81       11069.81
2022-12     10807.78  10807.78  10807.78  10807.78  10807.78       10807.78

[276 rows x 12 columns]

In [ ]:
for variable in macro_variables:
    input_file = input_path + variable + '.csv'
    data = pd.read_csv(input_file, header=0, index_col=0)
    data = data.astype(float) # set to float type
    data = data.drop(columns=['Ireland'])
    output_file = output_path + variable + '.csv'
    data.to_csv(output_file)
    print(variable, data)

inflation           Belgium   Denmark  Germany     Spain   France     Italy  \
Date
2000-01   1.77596   3.15941  1.54946   2.87824  1.53905   2.20386
2000-02   1.93566   3.00017  1.54762   2.96282  1.35533   2.38314
2000-03   2.24734   3.23875  1.54762   2.91720  1.49102   2.47027
2000-04   2.04885   3.05006  1.06635   2.96430  1.20727   2.28102
2000-05   2.16714   3.26875  0.94787   3.13872  1.39771   2.45902
...           ...       ...      ...       ...      ...       ...
2022-08   9.94416   8.90995  6.95652  10.54911  5.91313   8.37298
2022-09  11.27499  10.01890  8.57418   8.87199  5.55192   8.86559
2022-10  12.26795  10.11236  8.82071   7.26483  6.20047  11.83712
2022-11  10.62873   8.87021  8.80383   6.80956  6.15013  11.77024
2022-12  10.35079   8.72420  8.11843   5.70769  5.85072  11.63227

         Netherlands   Austria  Poland  Finland    Sweden  United States
Date
2000-01      1.79931   1.14974    10.1  2.26832   0.44805        2.73889
2000-02      1.91434   1.63934    10.4  2.78088   0.93123        3.22188
2000-03      1.93883   1.93989    10.3  3.14560   1.03253        3.75758
2000-04      1.88011   1.85792     9.8  2.64226   0.72040        3.06859
2000-05      2.17924   1.74530    10.0  2.69578   1.00897        3.18893
...              ...       ...     ...      ...       ...            ...
2022-08     11.95917   9.32039    16.1  7.61608   9.83168        8.26269
2022-09     14.53200  10.62802    17.2  8.11930  10.83762        8.20167
2022-10     14.32519  11.04707    17.9  8.31077  10.85325        7.74543
2022-11      9.87894  10.59160    17.5  9.13824  11.46453        7.11032
2022-12      9.58688  10.15180    16.6  9.14504  12.33864        6.45440

[276 rows x 12 columns]
unemployment          Belgium  Denmark  Germany  Spain  France  Italy  Netherlands  \
Date
2000-01      7.5      5.6      9.3   13.1     8.7   10.2          4.1
2000-02      7.2      4.9      9.3   12.8     8.7   11.1          4.2
2000-03      6.8      4.5      9.3   12.4     8.7   11.2          4.2
2000-04      6.7      4.3      9.3   12.0     8.7   10.7          3.9
2000-05      6.4      4.2      9.3   11.7     8.7   10.0          3.8
...          ...      ...      ...    ...     ...    ...          ...
2022-08      5.7      4.9      3.1   12.7     7.6    7.7          3.7
2022-09      5.6      4.5      2.9   13.0     7.2    7.9          3.9
2022-10      5.6      4.5      3.0   13.0     7.4    8.1          3.7
2022-11      5.6      4.7      3.0   12.9     7.3    7.8          3.5
2022-12      5.7      4.6      2.9   12.8     7.3    7.9          3.3

         Austria  Poland  Finland  Sweden  United States
Date
2000-01      5.0    15.9     10.6     6.5            4.5
2000-02      5.4    16.7     11.3     6.5            4.4
2000-03      5.3    17.0     11.2     6.1            4.3
2000-04      4.2    16.8     11.0     5.9            3.7
2000-05      3.2    16.3     11.9     5.5            3.8
...          ...     ...      ...     ...            ...
2022-08      4.9     2.9      6.7     6.6            3.8
2022-09      4.9     3.0      6.7     6.5            3.3
2022-10      4.3     2.9      5.8     7.1            3.4
2022-11      5.3     2.9      5.9     6.4            3.4
2022-12      4.8     2.9      6.7     6.9            3.3

[276 rows x 12 columns]
imports          Belgium  Denmark  Germany  Spain  France  Italy  Netherlands  \
Date
2000-01    0.512    0.575    0.527  0.574   0.662  0.608        0.468
2000-02    0.585    0.600    0.532  0.623   0.693  0.709        0.512
2000-03    0.657    0.703    0.623  0.708   0.797  0.805        0.574
2000-04    0.547    0.561    0.541  0.612   0.667  0.659        0.495
2000-05    0.646    0.676    0.645  0.749   0.788  0.800        0.557
...          ...      ...      ...    ...     ...    ...          ...
2022-08    2.003    1.682    1.744  1.742   1.532  1.741        2.077
2022-09    2.032    1.665    1.819  2.082   1.806  2.126        2.177
2022-10    1.850    1.607    1.767  1.870   1.633  1.956        2.211
2022-11    1.938    1.616    1.790  1.931   1.715  1.937        2.113
2022-12    1.746    1.492    1.552  1.824   1.660  1.748        1.931

         Austria  Poland  Finland  Sweden  United States
Date
2000-01    0.495   0.260    0.610   0.597          0.481
2000-02    0.576   0.301    0.675   0.651          0.506
2000-03    0.646   0.336    0.702   0.746          0.570
2000-04    0.564   0.308    0.698   0.666          0.525
2000-05    0.644   0.353    0.766   0.774          0.558
...          ...     ...      ...     ...            ...
2022-08    1.673   2.246    1.894   1.709          1.565
2022-09    1.845   2.459    1.777   1.801          1.521
2022-10    1.821   2.455    1.852   1.843          1.560
2022-11    1.921   2.483    1.829   1.871          1.416
2022-12    1.555   2.227    1.704   1.698          1.397

[276 rows x 12 columns]
exports          Belgium  Denmark  Germany  Spain  France  Italy  Netherlands  \
Date
2000-01    0.531    0.559    0.468  0.471   0.724  0.586        0.439
2000-02    0.595    0.608    0.517  0.535   0.788  0.718        0.471
2000-03    0.687    0.688    0.581  0.602   0.922  0.838        0.551
2000-04    0.572    0.559    0.504  0.512   0.771  0.662        0.465
2000-05    0.667    0.707    0.581  0.616   0.903  0.783        0.533
...          ...      ...      ...    ...     ...    ...          ...
2022-08    1.859    1.455    1.432  1.560   1.258  1.416        1.907
2022-09    2.100    1.634    1.583  1.911   1.535  1.906        2.118
2022-10    1.922    1.547    1.508  1.782   1.505  1.890        2.071
2022-11    1.959    1.629    1.603  2.021   1.502  1.991        2.082
2022-12    1.770    1.498    1.384  1.778   1.481  1.799        1.880

         Austria  Poland  Finland  Sweden  United States
Date
2000-01    0.478   0.162    0.861   0.680          0.477
2000-02    0.567   0.189    0.914   0.783          0.506
2000-03    0.651   0.204    1.053   0.910          0.570
2000-04    0.539   0.189    0.920   0.796          0.524
2000-05    0.655   0.194    1.125   0.904          0.535
...          ...     ...      ...     ...            ...
2022-08    1.508   2.015    1.703   1.492          1.503
2022-09    1.795   2.221    1.830   1.751          1.451
2022-10    1.711   2.248    1.747   1.690          1.494
2022-11    1.843   2.379    2.041   1.764          1.418
2022-12    1.507   1.930    1.712   1.631          1.397

[276 rows x 12 columns]
short_interest          Belgium   Denmark  Germany   Spain  France   Italy  Netherlands  \
Date
2000-01   3.3431  3.716429   3.3431  3.3431  3.3431  3.3431       3.3431
2000-02   3.5368  3.933214   3.5368  3.5368  3.5368  3.5368       3.5368
2000-03   3.7470  4.184783   3.7470  3.7470  3.7470  3.7470       3.7470
2000-04   3.9253  4.324500   3.9253  3.9253  3.9253  3.9253       3.9253
2000-05   4.3620  4.701304   4.3620  4.3620  4.3620  4.3620       4.3620
...          ...       ...      ...     ...     ...     ...          ...
2022-08   0.3947  0.694639   0.3947  0.3947  0.3947  0.3947       0.3947
2022-09   1.0109  1.344845   1.0109  1.0109  1.0109  1.0109       1.0109
2022-10   1.4277  1.801281   1.4277  1.4277  1.4277  1.4277       1.4277
2022-11   1.8252  2.090605   1.8252  1.8252  1.8252  1.8252       1.8252
2022-12   2.0635  2.332543   2.0635  2.0635  2.0635  2.0635       2.0635

         Austria  Poland  Finland  Sweden  United States
Date
2000-01   3.3431   17.34   3.3431  3.5700           5.95
2000-02   3.5368   18.59   3.5368  3.9000           6.01
2000-03   3.7470   18.30   3.7470  4.0600           6.14
2000-04   3.9253   18.52   3.9253  3.9900           6.28
2000-05   4.3620   18.42   4.3620  3.9600           6.71
...          ...     ...      ...     ...            ...
2022-08   0.3947    7.11   0.3947  1.5096           3.21
2022-09   1.0109    7.21   1.0109  1.6029           3.85
2022-10   1.4277    7.51   1.4277  1.6791           4.46
2022-11   1.8252    7.28   1.8252  2.0206           4.51
2022-12   2.0635    7.02   2.0635  2.0207           4.51

[276 rows x 12 columns]
exchange            Belgium    Denmark    Germany      Spain     France      Italy  \
Date
2000-01   93.79772   93.39124   93.00282   92.26925   92.72649   91.61323
2000-02   93.44784   92.93550   92.44779   91.90034   92.25468   91.12936
2000-03   92.93250   92.19206   91.71298   91.41938   91.62704   90.51184
2000-04   92.39873   91.51325   91.07752   90.94718   90.96730   89.94102
2000-05   91.94167   90.94299   90.35844   90.47710   90.31027   89.24510
...            ...        ...        ...        ...        ...        ...
2022-08  105.16184  105.49887  105.80185  106.50751  105.11258  106.27596
2022-09  105.42584  106.07979  106.04133  106.71227  105.32509  106.39949
2022-10  105.62602  106.50401  106.42910  106.90352  105.59478  106.69169
2022-11  106.07237  107.02437  107.00802  107.38157  106.23157  107.34309
2022-12  106.73061  107.96272  107.87722  108.08336  107.05387  108.21405

         Netherlands    Austria     Poland    Finland     Sweden  \
Date
2000-01     94.29399   96.03278   96.35902   91.44480   99.47383
2000-02     93.97458   95.73555   97.98132   90.93144   99.96042
2000-03     93.51943   95.31811  100.90500   90.20165  100.72712
2000-04     93.02732   94.95308   99.06461   89.54793  101.60174
2000-05     92.66889   94.56568   97.11633   88.92280  101.22257
...              ...        ...        ...        ...        ...
2022-08    105.22644  103.83084   93.09551  105.77866   93.23335
2022-09    105.56525  103.94802   92.99938  106.23835   91.19449
2022-10    105.80163  104.27237   91.96780  106.69189   90.17936
2022-11    106.17001  104.57964   94.27936  107.15274   91.15544
2022-12    106.77661  105.15177   94.93702  107.95624   90.86974

         United States
Date
2000-01       94.79080
2000-02       96.77677
2000-03       97.01539
2000-04       97.70828
2000-05      100.77761
...                ...
2022-08      115.58972
2022-09      118.83754
2022-10      120.72524
2022-11      116.89884
2022-12      114.30504

[276 rows x 12 columns]
ppi          Belgium  Denmark    Germany  Spain  France  Italy  Netherlands  \
Date
2000-01      0.0     73.9   84.96467   74.0    82.6   79.6         73.3
2000-02      0.0     74.2   85.22318   74.3    83.1   79.9         74.1
2000-03      0.0     74.6   85.39552   74.9    83.5   80.3         74.7
2000-04      0.0     74.8   85.56787   75.3    83.8   80.3         75.2
2000-05      0.0     75.4   85.91255   75.8    84.3   80.6         76.3
...          ...      ...        ...    ...     ...    ...          ...
2022-08    150.7    120.2  125.10000  131.8   125.8  125.1        145.9
2022-09    149.5    119.0  125.80000  131.8   126.0  125.6        144.9
2022-10    151.2    119.0  126.40000  133.1   127.6  126.6        146.7
2022-11    150.3    118.4  125.80000  132.4   126.7  126.2        143.4
2022-12    148.3    117.4  125.20000  130.3   125.5  125.3        140.0

           Austria  Poland  Finland     Sweden  United States
Date
2000-01   84.89748    81.4     94.8   82.84931       70.49313
2000-02   85.09087    81.8     96.7   82.95890       71.24764
2000-03   85.28426    82.1     97.4   82.73972       71.62490
2000-04   85.38096    82.6     97.8   82.63013       71.46322
2000-05   85.76773    83.2     97.7   83.06850       71.73269
...            ...     ...      ...        ...            ...
2022-08  123.73220   137.1    142.9  144.21920      135.53970
2022-09  124.38740   137.6    142.2  145.09590      135.82860
2022-10  123.95060   139.8    144.8  147.50690      136.88980
2022-11  122.96770   138.3    141.9  147.28770      136.27220
2022-12  122.64010   137.6    138.2  144.54790      131.74990

[276 rows x 12 columns]
bci            Belgium    Denmark   Germany     Spain     France     Italy  \
Date
2000-01  101.90070   99.62427  100.3090  101.8440  102.82630  102.2856
2000-02  102.07890   99.96683  100.4745  102.0418  103.07220  102.4286
2000-03  102.26730  100.31000  100.6211  102.2680  103.37340  102.5461
2000-04  102.35110  100.61050  100.7223  102.3859  103.62450  102.6167
2000-05  102.34450  101.00150  100.7990  102.4848  103.82650  102.6591
...            ...        ...       ...       ...        ...       ...
2022-08   99.41050  100.05740  101.7598  100.7619  100.68050  100.8058
2022-09   98.70477   99.71043  101.4529  100.6648  100.32700  100.5789
2022-10   98.27892   99.28343  101.2779  100.6375  100.08540  100.4865
2022-11   98.28242   99.02067  101.2210  100.5746   99.94704  100.5165
2022-12   98.55744   98.83118  101.2112  100.6686  100.00460  100.5885

         Netherlands    Austria     Poland    Finland    Sweden  United States
Date
2000-01     101.1353  101.36240   99.59469  102.11540  100.6497      100.79970
2000-02     101.1876  101.73750   99.60316  102.39860  100.8086      100.60210
2000-03     101.2673  102.06800   99.74757  102.42510  101.0151      100.40660
2000-04     101.3273  102.24890   99.97050  102.43470  101.1278      100.21440
2000-05     101.3891  102.36960  100.15040  102.61280  101.1876       99.98035
...              ...        ...        ...        ...       ...            ...
2022-08     101.0167  100.34790   98.29668  100.07540  102.5268       99.74149
2022-09     100.8111   99.89998   98.10536   99.58660  101.9829       99.51830
2022-10     100.7278   99.56224   98.08575   99.15176  101.5302       99.32158
2022-11     100.7509   99.40689   98.16630   98.87437  101.2879       99.16904
2022-12     100.7962   99.45175   98.35082   98.83807  101.0986       99.06271

[276 rows x 12 columns]
cci            Belgium    Denmark    Germany      Spain     France      Italy  \
Date
2000-01  102.31490   99.95573  100.53450  103.86120  102.05380  102.91200
2000-02  102.25260  100.02610  100.64690  104.00500  102.02850  102.84290
2000-03  102.12780  100.16460  100.71750  104.06750  102.13260  102.65840
2000-04  101.96930  100.37820  100.77350  103.96260  102.28440  102.49920
2000-05  101.96720  100.53840  100.85240  103.77910  102.37410  102.34960
...            ...        ...        ...        ...        ...        ...
2022-08   97.59071   96.35618   96.56208   94.41392   96.71279   96.95943
2022-09   97.11370   96.02613   96.23794   94.54726   96.66031   97.09666
2022-10   97.11466   95.86191   96.28996   94.95346   96.75361   97.60360
2022-11   97.59224   96.17754   96.69551   95.62205   96.87089   98.51060
2022-12   98.22021   96.63363   97.25648   96.33481   96.80460   99.14222

         Netherlands    Austria    Poland    Finland     Sweden  United States
Date
2000-01    102.27220  100.51890   0.00000  102.12150  101.89390      102.83620
2000-02    102.26110  100.16430   0.00000  102.15730  101.91820      102.89000
2000-03    102.26420  100.07970   0.00000  101.96250  101.94270      102.80770
2000-04    102.24110  100.11840   0.00000  101.73010  101.89450      102.78880
2000-05    102.18250  100.19970   0.00000  101.63960  101.80740      102.76310
...              ...        ...       ...        ...        ...            ...
2022-08     96.59209   95.76029  97.90965   94.63059   94.03212       96.35129
2022-09     96.29787   95.77724  97.66029   94.17392   93.24759       96.57005
2022-10     96.38996   95.92211  97.64581   94.08760   92.94206       96.68385
2022-11     96.76598   96.13065  97.84180   94.26894   93.15226       96.75018
2022-12     97.25465   96.39169  98.16346   94.68587   93.41302       96.97223

[276 rows x 12 columns]
construction           Belgium  Denmark   Germany      Spain  France  Italy  Netherlands  \
Date
2000-01  95.59203      0.0  101.5547  146.21970  104.85  127.5     110.1092
2000-02  98.59178      0.0  107.6446  146.51920  101.29  134.3     109.8092
2000-03  97.29189      0.0  101.3901  147.01820  106.11  131.5     107.5090
2000-04  99.09174      0.0  100.5671  147.51730  104.05  129.7     111.8093
2000-05  99.49171      0.0  100.7317  148.01630  109.61  135.5     114.1095
...           ...      ...       ...        ...     ...    ...          ...
2022-08  99.09174      0.0  131.5110   79.04849  101.05  134.6     133.6111
2022-09  98.09183      0.0  131.5110   77.95059  103.61  134.7     135.9113
2022-10  98.29181      0.0  135.2113   77.95059  104.65  133.6     138.4115
2022-11  99.89168      0.0  135.4113   77.85078  104.79  137.3     139.6116
2022-12  99.29173      0.0  123.5103   78.15022  103.15  137.9     140.7117

           Austria     Poland    Finland  Sweden  United States
Date
2000-01   73.89384   88.80740   63.30527    61.4       73.14061
2000-02   75.49371   84.50704   64.10534    62.1       73.96031
2000-03   75.89368   81.60680   63.70531    63.1       75.42529
2000-04   76.19365   82.20685   64.30536    60.5       74.98799
2000-05   76.09366   79.00658   64.70539    61.5       75.01026
...            ...        ...        ...     ...            ...
2022-08  130.08920  128.41070  119.91000   122.3      160.93630
2022-09  129.08920  120.91010  119.61000   124.8      161.80690
2022-10  129.98920  128.51070  118.30990   124.1      161.88270
2022-11  132.28900  131.51100  117.20980   123.7      164.74290
2022-12  128.78930  127.41060  118.30990   124.6      164.58290

[276 rows x 12 columns]
manufacturing          Belgium  Denmark   Germany     Spain     France     Italy  \
Date
2000-01     60.6     93.1  77.50668  126.0154  108.71910  125.8895
2000-02     64.7     93.1  79.41177  127.0383  109.19910  127.1894
2000-03     64.3     95.5  79.41177  130.3777  109.78910  128.5893
2000-04     67.0     94.7  80.41444  126.6116  110.40910  129.6892
2000-05     67.6    101.3  82.62032  129.1760  112.16910  130.8891
...          ...      ...       ...       ...        ...       ...
2022-08    119.0    144.2  95.55481  107.8380  101.39920  107.9910
2022-09    128.9    145.9  96.95856  107.9680  100.83920  106.1912
2022-10    127.3    141.6  96.35695  107.3720   98.79918  105.0912
2022-11    129.1    144.9  97.05882  107.8340  101.03920  105.2912
2022-12    125.8    167.1  95.65508  109.2000  101.07920  106.5911

         Netherlands    Austria     Poland  Finland  Sweden  United States
Date
2000-01     85.71587   65.45335   39.59670     92.5    96.3       95.51154
2000-02     86.59411   69.27423   40.39663     93.4   100.2       95.73273
2000-03     87.03323   68.85892   40.19665     93.2   101.2       96.35571
2000-04     86.24281   69.77261   41.49654     94.8   103.6       96.97421
2000-05     87.47234   71.43386   42.49646     96.5   104.7       96.96363
...              ...        ...        ...      ...     ...            ...
2022-08    120.37990  123.11030  154.28710    120.2   115.4      100.15120
2022-09    120.97980  123.61030  155.68700    121.6   120.7      100.39280
2022-10    120.57990  123.41030  155.68700    119.9   120.7      100.49560
2022-11    118.58020  124.81040  157.78680    119.4   117.2       99.80806
2022-12    119.98000  123.41030  158.28680    122.1   117.2       97.93153

[276 rows x 12 columns]
world          Belgium  Denmark  Germany  Spain  France  Italy  Netherlands  \
Date
2000-01     63.8     63.8     63.8   63.8    63.8   63.8         63.8
2000-02     65.0     65.0     65.0   65.0    65.0   65.0         65.0
2000-03     65.1     65.1     65.1   65.1    65.1   65.1         65.1
2000-04     65.6     65.6     65.6   65.6    65.6   65.6         65.6
2000-05     67.7     67.7     67.7   67.7    67.7   67.7         67.7
...          ...      ...      ...    ...     ...    ...          ...
2022-08    136.4    136.4    136.4  136.4   136.4  136.4        136.4
2022-09    136.6    136.6    136.6  136.6   136.6  136.6        136.6
2022-10    135.4    135.4    135.4  135.4   135.4  135.4        135.4
2022-11    132.7    132.7    132.7  132.7   132.7  132.7        132.7
2022-12    131.8    131.8    131.8  131.8   131.8  131.8        131.8

         Austria  Poland  Finland  Sweden  United States
Date
2000-01     63.8    63.8     63.8    63.8           63.8
2000-02     65.0    65.0     65.0    65.0           65.0
2000-03     65.1    65.1     65.1    65.1           65.1

In [ ]:
output_file = output_path + 'bond_yield' + '.csv'

input_file = input_path + 'oil' + '.csv'
data = pd.read_csv(input_file, header=0, index_col=0)
df2 = pd.DataFrame(index=data.index) # need to initialise with index in order to copy data over
df2 = df2.astype(float)

for country in countries:
    input_file = input_path + country + '.csv'

    data = pd.read_csv(input_file, header=0, index_col=0)
    data = data.astype(float) # set to float type
    data = data.drop(columns=['Open', 'High', 'Low', 'Change ']) # drop columns
    data = data[::-1]

    df2[country] = data["Price"]
    #data.to_csv(output_file) # save to csv

df2 = df2.iloc[::-1] # reverse rows

#change index to match other dataframes
df2.index = pd.to_datetime(df2.index, format = '%m/%d/%Y').strftime('%Y-%m')
df2.to_csv(output_file)

print(df2)

         Belgium  Denmark  Germany  Spain  France  Italy  Netherlands  \
Date
2000-01    5.853    5.883    5.539  5.817   5.682  5.824        5.691
2000-02    5.776    5.836    5.491  5.717   5.615  5.764        5.663
2000-03    5.501    5.561    5.223  5.461   5.333  5.518        5.370
2000-04    5.578    5.670    5.304  5.539   5.400  5.604        5.458
2000-05    5.552    5.709    5.177  5.508   5.345  5.558        5.336
...          ...      ...      ...    ...     ...    ...          ...
2022-08    2.183    1.903    1.536  2.736   2.150  3.883        1.872
2022-09    2.766    2.577    2.109  3.300   2.721  4.508        2.429
2022-10    2.746    2.541    2.150  3.255   2.685  4.325        2.437
2022-11    2.463    2.158    1.944  2.949   2.407  3.887        2.225
2022-12    3.201    2.810    2.563  3.657   3.113  4.692        2.913

         Austria  Poland  Finland  Sweden  United States
Date
2000-01    5.793  10.538    5.750   5.970          6.662
2000-02    5.757  10.775    5.750   5.835          6.409
2000-03    5.462  10.538    5.750   5.375          6.002
2000-04    5.562  11.498    5.750   5.450          6.218
2000-05    5.523  12.495    5.386   5.175          6.285
...          ...     ...      ...     ...            ...
2022-08    2.171   6.164    1.998   1.977          3.196
2022-09    2.818   7.164    2.794   2.255          3.829
2022-10    2.829   8.393    2.803   2.196          4.050
2022-11    2.534   6.616    2.532   1.858          3.611
2022-12    3.203   6.878    3.095   2.456          3.879

[276 rows x 12 columns]